### ISSUE TITLE
Compatibility with Flow 6

### ISSUE THREAD

**Issue by lorenzulrich** [flownative/flow-openidconnect-client#54]
Out of the box, this package is not fully compatible with Flow 6. The virtual object definition for the loggers only went into Flow 7 and higher as far as I can tell (https://github.com/neos/flow-development-collection/commit/a30d275b0dd741da91bd49455d1c1ef23e375d7a). Therefore, to make the package work in Flow 6, the following code needs to be added to the `Objects.yaml` of the project:

```
'Neos.Flow:SecurityLogger':
  className: Psr\Log\LoggerInterface
  scope: singleton
  factoryObjectName: Neos\Flow\Log\PsrLoggerFactoryInterface
  factoryMethodName: get
  arguments:
    1:
      value: securityLogger
```

As we are nearing EOL of Flow 6, I'm not sure how to proceed here. Just raise the dependency to Flow 7 or make a note in the readme?
